name: Beerxml Pipeline
on:
  push:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          pip install poetry==1.7.1
          poetry install
      - name: Run linting
        run: |
          poetry run ruff check ./beerxml
          poetry run bandit -r ./beerxml
  test-deploy-package:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Build and publish
        run: |
          pip install poetry==1.7.1
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build --dry-run
  deploy-package:
    needs: test-deploy-package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Build and publish
        run: |
          pip install poetry==1.7.1
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build